pipeline {
	agent {
		docker {
			image 'python:3.6.15-slim'
		}
	}

	stages{
		stage('build'){
			when{
				changeset "**/vote/**"
			}

			steps{
				echo 'Compiling vote app'

				dir('vote'){
					sh 'pip install -r requirements.txt'
				}
			}
		}

		stage('test'){
			when{
				changeset "**/vote/**"
			}

			steps{
				echo 'Running Unit Tests on vote app'

				dir('vote'){
					sh 'nosetests -v'
				}
			}
		}
	}

	post{
		always{
			echo 'Build pipeline for vote is completed..'
		}
	}
}
