pipeline {
	agent {
		docker{
			image 'maven:3.6.1-jdk-8-slim'
			args '-v $HOME/.m2:/root/.m2'
		}

	}


	stages{
		stage('build'){

			steps{
				echo 'Building worker app'

				dir('worker'){
					sh 'mvn compile'
				}
			}
		}

		stage('test'){

			steps{
				echo 'Running Unit Tests on worker app'

				dir('worker'){
					sh 'mvn clean test'
				}
			}
		}

		stage('package'){

			steps{
				echo 'Packaging worker app into a jarfile'

				dir('worker'){
					sh 'mvn package -DskipTests'
					archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
				}
			}
		}

		stage('docker-package'){

			when {
				changeset "**/worker/**"
			}

			steps{
				echo 'Packaging worker app with docker'

				script{
					docker.withRegistry('https://index.docker.io/v1/', 'DockerHub-ID') {
						def workerImage = docker.build("shirinchen2016/worker:v${env.BUILD_ID}", "./worker")
						workerImage.push()
						workerImage.push("${env.BRANCH_NAME}")
					}
				}

			}

		}

	}

	post{
		always{

			echo 'the job is completed..'
		}
	}
}
